"""empty message

Revision ID: cf6752f1e308
Revises: 5f465beeb738
Create Date: 2023-04-16 23:32:31.128030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6752f1e308'
down_revision = '5f465beeb738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_key', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['auth_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth_key')

    # ### end Alembic commands ###
